version: "3.8"

services:
  postgres:
    image: postgres
    container_name: photo-nas-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  web:
    build: .
    container_name: homecloud_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    volumes:
      - .:/app  # Mounts local code into the container
    command: ["flask", "run", "--host=0.0.0.0", "--port=${APP_PORT}", "--reload"]

volumes:
  postgres_data:
  pgadmin_data:
